llm: 
  model_name: "llama3.3:latest" # REQUIRED
  max_retries: 10 # REQUIRED
  retry_delay: 2 # REQUIRED
  api_url: "http://localhost:11434/api/generate"
  options:
    temperature: 0.1 # REQUIRED
    top_p: 0.1 # REQUIRED

output:
  format: "md" # REQUIRED (options include md or txt)
  log_file: "./src/data/transcript_processor.log" # REQUIRED

paths: 
  input_transcript: "./src/data/transcribed-text/" # REQUIRED 
  output_directory: "./src/data/meeting-summaries" # REQUIRED
  audio_file: "./src/data/raw-audio/Armory Audio.m4a" # REQUIRED

audio:
  output_format: "mp3" # REQUIRED (options include wav or mp3)

audio_processing:  # Section for audio conversion paths
  converted_audio_directory: "./src/data/converted_audio"

transcription:
  model_selection: "base" # REQUIRED (options include tiny, base, small, medium, large)
  transcription_directory: "./src/data/transcribed-text" # REQUIRED

prompts:
  summary_prompt: |
    Analyze the provided transcript and create a comprehensive Summary Report that captures all essential information.
    
    Structure the summary as follows:
    
    1. EXECUTIVE OVERVIEW
    - Synthesize core meeting purpose and outcomes
    - Highlight critical decisions and strategic implications
    - Emphasize time-sensitive matters and key commitments
    - Identify potential risks and mitigation strategies
        
    2. KEY DISCUSSION POINTS
    - Present main topics chronologically with timestamps
    - Include relevant context and supporting details
    - Document specific decisions, agreements, and dissenting views
    - Capture technical specifications and requirements where applicable
    - Highlight cross-functional dependencies and impacts
    - Note areas requiring additional research or clarification
    - Record key stakeholder concerns and proposed solutions
    
    3. ACTION ITEMS AND RESPONSIBILITIES
    - List concrete tasks with clear ownership and deliverables
    - Include specific timelines and dependencies
    - Note required resources or prerequisites
    - Document success criteria and acceptance metrics
    - Identify potential blockers and contingency plans
    - Track related tasks and downstream impacts
    
    4. CONCLUSIONS AND NEXT STEPS
    - Summarize achieved outcomes against objectives
    - List immediate next actions with owners
    - Document any pending decisions or open issues
    - Note scheduled follow-ups and key milestones
    - Outline communication plan for key stakeholders
    - Identify required changes to existing plans or processes
    
    Format Guidelines:
    - Use clear, professional language with consistent terminology
    - Maintain objective tone and avoid ambiguous language
    - Present information in order of importance within each section
    - Use hierarchical bullet points for clarity and relationships
    - Include specific quotes only for critical decisions or commitments
    - Use standardized formatting for dates, times, and priorities
    - Highlight assumptions and dependencies explicitly
    - Maintain consistent verb tense throughout the document
    - Use active voice for action items and responsibilities

document_format:
  metadata:
    header: "## Meeting Metadata"
    fields:
      - date
      - duration
      - participants
      - location
      - meeting_type
    date_format: "%Y-%m-%d %H:%M:%S"
    defaults:
      participants: "YOUR_INPUT_HERE" # OPTIONAL
      location: "YOUR_INPUT_HERE" # OPTIONAL
      meeting_type: "YOUR_INPUT_HERE" # OPTIONAL
  
  template: |
    # Meeting Summary Report

    {metadata_section}

    {summary}

    ---
    Generated on: {generation_timestamp}